### ISSUE TITLE
Doesn't working?

### ISSUE THREAD

**Issue by oieduardorabelo** [indrekpaas/aria-attributes-and-roles#1]
Hi!

I installed via Package Control, but, it does not seem to be working...

![](https://dl.dropboxusercontent.com/s/prfb9w534sdo24g/Screen%20Shot%202015-05-22%20at%208.09.27%20PM.png)

![](https://dl.dropboxusercontent.com/s/numb0h6gu4gqkcs/Screen%20Shot%202015-05-22%20at%208.10.22%20PM.png)

**Comment by Lewiscowles1986** [comment]
![sublime aria working](https://cloud.githubusercontent.com/assets/2605791/8621924/428b8952-2720-11e5-9a28-90b4ed94d324.png)

Works for me, I do set syntax highlighting to html, make a body tag, then go in and `<CTRL>`+`<Space>`

**Comment by indrekpaas** [comment]
@oieduardorabelo sorry for the late reply. What version of Sublime Text and what theme are you using? This would help me in hunting down the issue.

Cheers!

**Comment by oieduardorabelo** [comment]
no worries @indrekpaas :smile: 

even with the HTML syntax @Lewiscowles1986 , doesn't work for me! :sob: 

#### Sublime version
![Sublime Version](https://dl.dropboxusercontent.com/s/a1v49z87bogv2vo/Screen%20Shot%202015-07-13%20at%201.45.22%20pm.png)

#### Sublime installed packages
![Installed packages](https://dl.dropboxusercontent.com/s/w8w2v04h6bqhld8/Screen%20Shot%202015-07-13%20at%201.46.09%20pm.png)

#### Sublime with HTML syntax
![HTML syntax](https://dl.dropboxusercontent.com/s/flu8otf5v4weqzg/Screen%20Shot%202015-07-13%20at%201.46.27%20pm.png)


#### OS version
![OS version](https://dl.dropboxusercontent.com/s/l80j7o0jfulnut8/Screen%20Shot%202015-07-13%20at%201.48.57%20pm%20%281%29.png)

**Comment by indrekpaas** [comment]
A comment from @FichteFoll:

> Taking a closer look, I think the reason why the completions won't show up in ST3 because the HTML completions are provided by a Python plugin that hides all other completions by default.

Until I rewrite this plugin to support Sublime Text 3, it can only be used with Sublime Text 2.

**Comment by oieduardorabelo** [comment]
cool, thank you for the feedback @indrekpaas :+1:

**Comment by FichteFoll** [comment]
@oieduardorabelo you can take a look at https://github.com/SublimeTextIssues/DefaultPackages/issues/118 on how to fix it for you locally, but unfortunately there isn't really a good way to do this override on all installations of this package.

**Comment by oieduardorabelo** [comment]
good tip @FichteFoll , I'll try here! :smile:

**Comment by indrekpaas** [comment]
@oieduardorabelo This package has now been updated with added support for Sublime Text 3. Until @FichteFoll makes it available on Package Control you can install it manually. Cheers!

**Comment by oieduardorabelo** [comment]
awesome @indrekpaas , thanks a lot for the work guys! I'll try it right now
